-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "TPFinal"."CI_Class"
(
    "idClass" integer NOT NULL DEFAULT nextval('"TPFinal"."CI_Class_idClass_seq"'::regclass),
    "className" character(30) COLLATE pg_catalog."default",
    "classSubtype" character(30) COLLATE pg_catalog."default",
    "classFunction" character(30) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Class_ID" PRIMARY KEY ("idClass")
);

CREATE TABLE IF NOT EXISTS "TPFinal"."CI_Location"
(
    "idLocation" integer NOT NULL DEFAULT nextval('"TPFinal"."CI_Location_idLocation_seq"'::regclass),
    "locationName" character(75) COLLATE pg_catalog."default",
    "locationDescription" character(100) COLLATE pg_catalog."default",
    "locationAddress" character(200) COLLATE pg_catalog."default",
    "locationCountry" character(80) COLLATE pg_catalog."default",
    "locationCity" character(100) COLLATE pg_catalog."default",
    "locationZip" character(15) COLLATE pg_catalog."default",
    "locationLat" real,
    "locationLong" real,
    "locationGeopoint" geometry,
    CONSTRAINT "PK_Location_ID" PRIMARY KEY ("idLocation")
);

CREATE TABLE IF NOT EXISTS "TPFinal"."CI_Status"
(
    "statusID" integer NOT NULL DEFAULT nextval('"TPFinal"."CI_Status_statusID_seq"'::regclass),
    "statusName" character(20) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Status_ID" PRIMARY KEY ("statusID")
);

CREATE TABLE IF NOT EXISTS "TPFinal"."CI_Table"
(
    "idCi" integer NOT NULL DEFAULT nextval('"TPFinal"."CI_Table_idCi_seq"'::regclass),
    "ciName" character(20) COLLATE pg_catalog."default",
    "ciBrand" character(20) COLLATE pg_catalog."default",
    "ciModel" character(50) COLLATE pg_catalog."default",
    "ciLocationID" integer,
    "ciClassID" integer,
    "ciPurchaseDate" date,
    "ciStatusID" integer,
    CONSTRAINT "PK_CI_ID" PRIMARY KEY ("idCi")
);

CREATE TABLE IF NOT EXISTS "TPFinal"."CI_Topology"
(
    "topologyID" integer NOT NULL DEFAULT nextval('"TPFinal"."ciTopology_topologyID_seq"'::regclass),
    "timestamp" date,
    "ciID" integer,
    "neighborID" integer,
    interface character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT "ciTopology_pkey" PRIMARY KEY ("topologyID")
);

ALTER TABLE IF EXISTS "TPFinal"."CI_Table"
    ADD CONSTRAINT "ciClassID" FOREIGN KEY ("ciClassID")
    REFERENCES "TPFinal"."CI_Class" ("idClass") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "TPFinal"."CI_Table"
    ADD CONSTRAINT "ciLocationID" FOREIGN KEY ("ciLocationID")
    REFERENCES "TPFinal"."CI_Location" ("idLocation") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "TPFinal"."CI_Table"
    ADD CONSTRAINT "ciStatusID" FOREIGN KEY ("ciStatusID")
    REFERENCES "TPFinal"."CI_Status" ("statusID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "TPFinal"."CI_Topology"
    ADD CONSTRAINT "CI_ID" FOREIGN KEY ("ciID")
    REFERENCES "TPFinal"."CI_Table" ("idCi") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS "TPFinal"."CI_Topology"
    ADD CONSTRAINT "NeighborID" FOREIGN KEY ("neighborID")
    REFERENCES "TPFinal"."CI_Table" ("idCi") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;